# Plugin info
api-version: "1.16"
name: "Dice"
description: "A plugin that allows you to teleport the player to a random safe place."
version: "1.3-rc1"
main: "org.xtimms.dice.DicePlugin"
database: false

# Authors
author: "Xtimms"
authors: []

permissions:
  dice.command.rtp:
    default: op
  dice.cooldown.bypass:
    default: op

commands:
  rtp:
    description: Teleports you to a random location inside the worldborder
    permission: dice.command.rtp
    aliases: []